name: Release NPM

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - run: npm install -g npm@latest
      - run: npm ci
      - run: npm run build

      - id: check-tag
        run: |
          if [[ "${GITHUB_REF_NAME}" =~ -rc[0-9]+$ ]]; then
            echo "rc=true" >> "$GITHUB_OUTPUT"
          else
            echo "rc=false" >> "$GITHUB_OUTPUT"
          fi

      - if: steps.check-tag.outputs.rc == 'true'
        run: npm publish --access public --tag rc
      - if: steps.check-tag.outputs.rc == 'false'
        run: npm publish --access public
